on:
    push:
        branches:
            - main

name: ðŸš€ Deploy website on push
jobs:
    web-deploy:
        name: ðŸŽ‰ Deploy
        runs-on: ubuntu-latest
        steps:
            - name: ðŸšš Get latest code
              uses: actions/checkout@v3
            - uses: actions/setup-node@master
            - name: Copy files (index.php, .htaccess, .env) for shared hosting
              run: |
                  php -r "foreach (new DirectoryIterator(__DIR__ . '/.public_html') as \$file) {
                    if (!\$file->isDot() && \$file->isFile()) {
                      copy(\$file->getPathname(), __DIR__ . '/src/' . \$file->getFilename());
                    }
                  }"
            - name: Install Dependencies
              run: |
                  cd src
                  composer install
            - name: Generate key
              run: |
                  cd src
                  php artisan key:generate
            - name: Generate storage link
              run: |
                  cd src
                  php artisan storage:link
            - name: Directory Permissions
              run: |
                  cd src
                  chmod -R 777 storage bootstrap/cache
            - name: ðŸ“‚ Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.3.4
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  local-dir: ./src/
                  server-dir: ./update/
                  password: ${{ secrets.FTP_PASSWORD }}
